Add README

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -26,4 +26,8 @@ jobs:
         with:
           file: test/badly-formatted.tex
           config: test/latexindent.yaml
+      - if: steps.badcheck.outcome != "failure"
+        run: |
+          echo "The action should have failed on a badly-formatted file!"
+          exit 1
 
